name: build

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Login to Github Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Set env
        run: |
          IMAGE_ID=ghcr.io/kangaroohealthscience/${{ github.event.repository.name }}:latest
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV

      - name: Build image
        run: docker build . -t $IMAGE_ID

      - name: Push image
        run: docker push $IMAGE_ID
